// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function Dummy(arg1:COM3D2.Anm,arg2:COM3D2.PropertyCurve,arg3:COM3D2.BoneCurveData,arg4:COM3D2.Keyframe):Promise<void>;
