// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertAnmToJson(arg1, arg2) {
  return window['go']['COM3D2']['AnmService']['ConvertAnmToJson'](arg1, arg2);
}

export function ConvertJsonToAnm(arg1, arg2) {
  return window['go']['COM3D2']['AnmService']['ConvertJsonToAnm'](arg1, arg2);
}

export function ReadAnmFile(arg1) {
  return window['go']['COM3D2']['AnmService']['ReadAnmFile'](arg1);
}

export function WriteAnmFile(arg1, arg2) {
  return window['go']['COM3D2']['AnmService']['WriteAnmFile'](arg1, arg2);
}
