// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertAnmToJson(arg1:string,arg2:string):Promise<void>;

export function ConvertJsonToAnm(arg1:string,arg2:string):Promise<void>;

export function ReadAnmFile(arg1:string):Promise<COM3D2.Anm>;

export function WriteAnmFile(arg1:string,arg2:COM3D2.Anm):Promise<void>;
