// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dummy(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['COM3D2']['ColModel']['Dummy'](arg1, arg2, arg3, arg4, arg5, arg6);
}
