// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function Dummy(arg1:COM3D2.Col,arg2:COM3D2.DynamicBoneColliderBase,arg3:COM3D2.DynamicBoneCollider,arg4:COM3D2.DynamicBoneMuneCollider,arg5:COM3D2.DynamicBonePlaneCollider,arg6:COM3D2.MissingCollider):Promise<void>;
