// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertColToJson(arg1, arg2) {
  return window['go']['COM3D2']['ColService']['ConvertColToJson'](arg1, arg2);
}

export function ConvertJsonToCol(arg1, arg2) {
  return window['go']['COM3D2']['ColService']['ConvertJsonToCol'](arg1, arg2);
}

export function ReadColFile(arg1) {
  return window['go']['COM3D2']['ColService']['ReadColFile'](arg1);
}

export function WriteColFile(arg1, arg2) {
  return window['go']['COM3D2']['ColService']['WriteColFile'](arg1, arg2);
}
