// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertColToJson(arg1:string,arg2:string):Promise<void>;

export function ConvertJsonToCol(arg1:string,arg2:string):Promise<void>;

export function ReadColFile(arg1:string):Promise<COM3D2.Col>;

export function WriteColFile(arg1:string,arg2:COM3D2.Col):Promise<void>;
