// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenModFile(arg1:string):Promise<any>;

export function SaveModFile(arg1:string,arg2:any):Promise<void>;
