// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileTypeDetermine(arg1, arg2) {
  return window['go']['COM3D2']['CommonService']['FileTypeDetermine'](arg1, arg2);
}
