// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function FileTypeDetermine(arg1:string):Promise<COM3D2.FileType>;
