// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDiffGeneration(arg1) {
  return window['go']['COM3D2']['DiffGeneratorService']['AnalyzeDiffGeneration'](arg1);
}

export function AnalyzeMateVariantBase(arg1) {
  return window['go']['COM3D2']['DiffGeneratorService']['AnalyzeMateVariantBase'](arg1);
}

export function AnalyzeMenuVariantBases(arg1) {
  return window['go']['COM3D2']['DiffGeneratorService']['AnalyzeMenuVariantBases'](arg1);
}

export function GenerateDiffFiles(arg1) {
  return window['go']['COM3D2']['DiffGeneratorService']['GenerateDiffFiles'](arg1);
}

export function GenerateMateVariants(arg1) {
  return window['go']['COM3D2']['DiffGeneratorService']['GenerateMateVariants'](arg1);
}

export function GenerateMenuVariants(arg1) {
  return window['go']['COM3D2']['DiffGeneratorService']['GenerateMenuVariants'](arg1);
}
