// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function AnalyzeDiffGeneration(arg1:string):Promise<COM3D2.DiffGenerationAnalysis>;

export function AnalyzeMateVariantBase(arg1:string):Promise<COM3D2.MateVariantAnalysis>;

export function AnalyzeMenuVariantBases(arg1:Array<string>):Promise<COM3D2.MenuVariantAnalysis>;

export function GenerateDiffFiles(arg1:COM3D2.DiffGenerationRequest):Promise<COM3D2.DiffGenerationResult>;

export function GenerateMateVariants(arg1:COM3D2.MateVariantGenerationRequest):Promise<COM3D2.DiffGenerationResult>;

export function GenerateMenuVariants(arg1:COM3D2.MenuVariantGenerationRequest):Promise<COM3D2.DiffGenerationResult>;
