// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function Dummy(arg1:COM3D2.Mate,arg2:COM3D2.Material,arg3:COM3D2.TexProperty,arg4:COM3D2.Tex2DSubProperty,arg5:COM3D2.TexRTSubProperty,arg6:COM3D2.ColProperty,arg7:COM3D2.VecProperty,arg8:COM3D2.FProperty):Promise<void>;
