// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadMateFile(arg1) {
  return window['go']['COM3D2']['MateService']['ReadMateFile'](arg1);
}

export function SaveMateFile(arg1, arg2) {
  return window['go']['COM3D2']['MateService']['SaveMateFile'](arg1, arg2);
}
