// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertJsonToMate(arg1:string,arg2:string):Promise<void>;

export function ConvertMateToJson(arg1:string,arg2:string):Promise<void>;

export function ReadMateFile(arg1:string):Promise<COM3D2.Mate>;

export function WriteMateFile(arg1:string,arg2:COM3D2.Mate):Promise<void>;
