// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadMenuFile(arg1) {
  return window['go']['COM3D2']['MenuService']['ReadMenuFile'](arg1);
}

export function SaveMenuFile(arg1, arg2) {
  return window['go']['COM3D2']['MenuService']['SaveMenuFile'](arg1, arg2);
}
