// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToMenu(arg1, arg2) {
  return window['go']['COM3D2']['MenuService']['ConvertJsonToMenu'](arg1, arg2);
}

export function ConvertMenuToJson(arg1, arg2) {
  return window['go']['COM3D2']['MenuService']['ConvertMenuToJson'](arg1, arg2);
}

export function ReadMenuFile(arg1) {
  return window['go']['COM3D2']['MenuService']['ReadMenuFile'](arg1);
}

export function WriteMenuFile(arg1, arg2) {
  return window['go']['COM3D2']['MenuService']['WriteMenuFile'](arg1, arg2);
}
