// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertJsonToMenu(arg1:string,arg2:string):Promise<void>;

export function ConvertMenuToJson(arg1:string,arg2:string):Promise<void>;

export function ReadMenuFile(arg1:string):Promise<COM3D2.Menu>;

export function WriteMenuFile(arg1:string,arg2:COM3D2.Menu):Promise<void>;
