// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ReadMenuFile(arg1:string):Promise<COM3D2.Menu>;

export function SaveMenuFile(arg1:string,arg2:COM3D2.Menu):Promise<void>;
