// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function Dummy(arg1:COM3D2.Model,arg2:COM3D2.Bone,arg3:COM3D2.Vertex,arg4:COM3D2.Vertex,arg5:COM3D2.BoneWeight,arg6:COM3D2.Matrix4x4,arg7:COM3D2.MorphData,arg8:COM3D2.SkinThickness,arg9:COM3D2.ThickGroup,arg10:COM3D2.ThickPoint,arg11:COM3D2.ThickDefPerAngle,arg12:COM3D2.Vector2,arg13:COM3D2.Vector3,arg14:COM3D2.Quaternion,arg15:COM3D2.Material):Promise<void>;
