// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToModel(arg1, arg2) {
  return window['go']['COM3D2']['ModelService']['ConvertJsonToModel'](arg1, arg2);
}

export function ConvertModelToJson(arg1, arg2) {
  return window['go']['COM3D2']['ModelService']['ConvertModelToJson'](arg1, arg2);
}

export function ReadModelFile(arg1) {
  return window['go']['COM3D2']['ModelService']['ReadModelFile'](arg1);
}

export function ReadModelMaterial(arg1) {
  return window['go']['COM3D2']['ModelService']['ReadModelMaterial'](arg1);
}

export function ReadModelMetadata(arg1) {
  return window['go']['COM3D2']['ModelService']['ReadModelMetadata'](arg1);
}

export function WriteModelFile(arg1, arg2) {
  return window['go']['COM3D2']['ModelService']['WriteModelFile'](arg1, arg2);
}

export function WriteModelMaterial(arg1, arg2, arg3) {
  return window['go']['COM3D2']['ModelService']['WriteModelMaterial'](arg1, arg2, arg3);
}

export function WriteModelMetadata(arg1, arg2, arg3) {
  return window['go']['COM3D2']['ModelService']['WriteModelMetadata'](arg1, arg2, arg3);
}
