// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertJsonToModel(arg1:string,arg2:string):Promise<void>;

export function ConvertModelToJson(arg1:string,arg2:string):Promise<void>;

export function ReadModelFile(arg1:string):Promise<COM3D2.Model>;

export function ReadModelMaterial(arg1:string):Promise<Array<COM3D2.Material>>;

export function ReadModelMetadata(arg1:string):Promise<COM3D2.ModelMetadata>;

export function WriteModelFile(arg1:string,arg2:COM3D2.Model):Promise<void>;

export function WriteModelMaterial(arg1:string,arg2:string,arg3:Array<COM3D2.Material>):Promise<void>;

export function WriteModelMetadata(arg1:string,arg2:string,arg3:COM3D2.ModelMetadata):Promise<void>;
