// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadModelFile(arg1) {
  return window['go']['COM3D2']['ModelService']['ReadModelFile'](arg1);
}

export function WriteModelFile(arg1, arg2) {
  return window['go']['COM3D2']['ModelService']['WriteModelFile'](arg1, arg2);
}
