// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function CSVFileToNei(arg1:string):Promise<COM3D2.Nei>;

export function CSVFileToNeiFile(arg1:string,arg2:string):Promise<void>;

export function CSVToNei(arg1:Array<any>):Promise<COM3D2.Nei>;

export function NeiFileToCSV(arg1:string):Promise<Array<any>>;

export function NeiFileToCSVFile(arg1:string,arg2:string):Promise<void>;

export function NeiToCSV(arg1:COM3D2.Nei):Promise<Array<any>>;

export function NeiToCSVFile(arg1:COM3D2.Nei,arg2:string):Promise<void>;

export function ReadNeiFile(arg1:string):Promise<COM3D2.Nei>;

export function WriteNeiFile(arg1:COM3D2.Nei,arg2:string):Promise<void>;
