// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CSVFileToNei(arg1) {
  return window['go']['COM3D2']['NeiService']['CSVFileToNei'](arg1);
}

export function CSVFileToNeiFile(arg1, arg2) {
  return window['go']['COM3D2']['NeiService']['CSVFileToNeiFile'](arg1, arg2);
}

export function CSVToNei(arg1) {
  return window['go']['COM3D2']['NeiService']['CSVToNei'](arg1);
}

export function NeiFileToCSV(arg1) {
  return window['go']['COM3D2']['NeiService']['NeiFileToCSV'](arg1);
}

export function NeiFileToCSVFile(arg1, arg2) {
  return window['go']['COM3D2']['NeiService']['NeiFileToCSVFile'](arg1, arg2);
}

export function NeiToCSV(arg1) {
  return window['go']['COM3D2']['NeiService']['NeiToCSV'](arg1);
}

export function NeiToCSVFile(arg1, arg2) {
  return window['go']['COM3D2']['NeiService']['NeiToCSVFile'](arg1, arg2);
}

export function ReadNeiFile(arg1) {
  return window['go']['COM3D2']['NeiService']['ReadNeiFile'](arg1);
}

export function WriteNeiFile(arg1, arg2) {
  return window['go']['COM3D2']['NeiService']['WriteNeiFile'](arg1, arg2);
}
