// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function Dummy(arg1:COM3D2.Phy,arg2:COM3D2.AnimationCurve,arg3:COM3D2.Keyframe,arg4:COM3D2.BoneValue):Promise<void>;
