// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToPhy(arg1, arg2) {
  return window['go']['COM3D2']['PhyService']['ConvertJsonToPhy'](arg1, arg2);
}

export function ConvertPhyToJson(arg1, arg2) {
  return window['go']['COM3D2']['PhyService']['ConvertPhyToJson'](arg1, arg2);
}

export function ReadPhyFile(arg1) {
  return window['go']['COM3D2']['PhyService']['ReadPhyFile'](arg1);
}

export function WritePhyFile(arg1, arg2) {
  return window['go']['COM3D2']['PhyService']['WritePhyFile'](arg1, arg2);
}
