// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertJsonToPhy(arg1:string,arg2:string):Promise<void>;

export function ConvertPhyToJson(arg1:string,arg2:string):Promise<void>;

export function ReadPhyFile(arg1:string):Promise<COM3D2.Phy>;

export function WritePhyFile(arg1:string,arg2:COM3D2.Phy):Promise<void>;
