// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertJsonToPMat(arg1:string,arg2:string):Promise<void>;

export function ConvertPMatToJson(arg1:string,arg2:string):Promise<void>;

export function ReadPMatFile(arg1:string):Promise<COM3D2.PMat>;

export function WritePMatFile(arg1:string,arg2:COM3D2.PMat):Promise<void>;
