// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadPMatFile(arg1) {
  return window['go']['COM3D2']['PMatService']['ReadPMatFile'](arg1);
}

export function WritePMatFile(arg1, arg2) {
  return window['go']['COM3D2']['PMatService']['WritePMatFile'](arg1, arg2);
}
