// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function Dummy(arg1:COM3D2.Psk,arg2:COM3D2.PanierRadiusGroup,arg3:COM3D2.AnimationCurve,arg4:COM3D2.Vector3):Promise<void>;
