// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToPsk(arg1, arg2) {
  return window['go']['COM3D2']['PskService']['ConvertJsonToPsk'](arg1, arg2);
}

export function ConvertPskToJson(arg1, arg2) {
  return window['go']['COM3D2']['PskService']['ConvertPskToJson'](arg1, arg2);
}

export function ReadPskFile(arg1) {
  return window['go']['COM3D2']['PskService']['ReadPskFile'](arg1);
}

export function WritePskFile(arg1, arg2) {
  return window['go']['COM3D2']['PskService']['WritePskFile'](arg1, arg2);
}
