// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertJsonToPsk(arg1:string,arg2:string):Promise<void>;

export function ConvertPskToJson(arg1:string,arg2:string):Promise<void>;

export function ReadPskFile(arg1:string):Promise<COM3D2.Psk>;

export function WritePskFile(arg1:string,arg2:COM3D2.Psk):Promise<void>;
