// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function ConvertImageToTex(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<COM3D2.Tex>;

export function ConvertTexToImage(arg1:COM3D2.Tex,arg2:string,arg3:boolean):Promise<void>;

export function ReadTexFile(arg1:string):Promise<COM3D2.Tex>;

export function WriteTexFile(arg1:string,arg2:COM3D2.Tex):Promise<void>;
