// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {COM3D2} from '../models';

export function CheckImageMagick():Promise<boolean>;

export function ConvertAnyToAnyAndWrite(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;

export function ConvertAnyToPng(arg1:string):Promise<string>;

export function ConvertImageToTex(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<COM3D2.Tex>;

export function ConvertImageToTexAndWrite(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;

export function ConvertTexToImageAndWrite(arg1:COM3D2.Tex,arg2:string,arg3:boolean):Promise<void>;

export function CovertTexToImage(arg1:string,arg2:boolean):Promise<COM3D2.CovertTexToImageResult>;

export function ReadTexFile(arg1:string):Promise<COM3D2.Tex>;

export function WriteTexFile(arg1:string,arg2:COM3D2.Tex):Promise<void>;
