// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImageToTex(arg1, arg2, arg3, arg4) {
  return window['go']['COM3D2']['TexService']['ConvertImageToTex'](arg1, arg2, arg3, arg4);
}

export function ConvertImageToTexAndWrite(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['COM3D2']['TexService']['ConvertImageToTexAndWrite'](arg1, arg2, arg3, arg4, arg5);
}

export function ConvertTexToImageAndWrite(arg1, arg2, arg3) {
  return window['go']['COM3D2']['TexService']['ConvertTexToImageAndWrite'](arg1, arg2, arg3);
}

export function CovertTexToImage(arg1, arg2) {
  return window['go']['COM3D2']['TexService']['CovertTexToImage'](arg1, arg2);
}

export function ReadTexFile(arg1) {
  return window['go']['COM3D2']['TexService']['ReadTexFile'](arg1);
}

export function WriteTexFile(arg1, arg2) {
  return window['go']['COM3D2']['TexService']['WriteTexFile'](arg1, arg2);
}
