// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLatestVersion() {
  return window['go']['main']['App']['CheckLatestVersion']();
}

export function CompareVersions(arg1, arg2) {
  return window['go']['main']['App']['CompareVersions'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function IsSupportedImageType(arg1) {
  return window['go']['main']['App']['IsSupportedImageType'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}
