// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckLatestVersion():Promise<main.VersionCheckResult>;

export function GetAppVersion():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;
