// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {fs} from '../models';

export function CheckLatestVersion():Promise<main.VersionCheckResult>;

export function CompareVersions(arg1:string,arg2:string):Promise<boolean>;

export function GetAppVersion():Promise<string>;

export function GetFileInfo(arg1:string):Promise<fs.FileInfo>;

export function GetFileSize(arg1:string):Promise<number>;

export function IsSupportedImageType(arg1:string):Promise<boolean>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SelectPathToSave(arg1:string,arg2:string):Promise<string>;
